name: Deploy Project

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Install dependecies
        run: npm ci
      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Install dependecies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy Project
        run: echo "Deploying Project..."
